{
  "instructors": [
    {
      "id": 1,
      "firstName": "רחל",
      "lastName": "כהן",
      "idNumber": "123456789",
      "email": "rachel.cohen@education.gov.il",
      "phone": "050-1234567",
      "username": "rachel_cohen",
      "password": "$2b$10$8K1p/a0drtIzwqL8XXXXX.xXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "role": "instructor",
      "status": "active",
      "createdDate": "2024-01-15T08:30:00Z"
    },
    {
      "id": 2,
      "firstName": "מרים",
      "lastName": "שלום",
      "idNumber": "987654321",
      "email": "miriam.shalom@education.gov.il",
      "phone": "052-9876543",
      "username": "miriam_shalom",
      "password": "$2b$10$9L2q/b1esujJzxrM9XXXXX.xXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "role": "instructor",
      "status": "active",
      "createdDate": "2024-02-20T10:15:00Z"
    },
    {
      "id": 3,
      "firstName": "אבי",
      "lastName": "גולד",
      "idNumber": "456789123",
      "email": "avi.gold@education.gov.il",
      "phone": "054-4567891",
      "username": "dr_gold",
      "password": "$2b$10$7J3m/c2ftvkKaxsN8XXXXX.xXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "role": "instructor",
      "status": "active",
      "createdDate": "2024-01-10T14:20:00Z"
    },
    {
      "id": 4,
      "firstName": "רונית",
      "lastName": "לוי",
      "idNumber": "789123456",
      "email": "ronit.levi@education.gov.il",
      "phone": "053-7891234",
      "username": "ronit_levi",
      "password": "$2b$10$6I4n/d3guwlLbyoO9XXXXX.xXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "role": "instructor",
      "status": "active",
      "createdDate": "2024-03-05T09:45:00Z"
    },
    {
      "id": 5,
      "firstName": "תמר",
      "lastName": "כהן",
      "idNumber": "321654987",
      "email": "tamar.cohen@education.gov.il",
      "phone": "050-3216549",
      "username": "tamar_cohen",
      "password": "$2b$10$5H5o/e4hvxmMczpP0XXXXX.xXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "role": "instructor",
      "status": "active",
      "createdDate": "2024-02-12T11:30:00Z"
    },
    {
      "id": 6,
      "firstName": "עינת",
      "lastName": "שמש",
      "idNumber": "654987321",
      "email": "einat.shemesh@education.gov.il",
      "phone": "052-6549873",
      "username": "dr_shemesh",
      "password": "$2b$10$4G6p/f5iwynNdaqQ1XXXXX.xXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "role": "instructor",
      "status": "active",
      "createdDate": "2024-01-28T16:00:00Z"
    },
    {
      "id": 7,
      "firstName": "דוד",
      "lastName": "אברהם",
      "idNumber": "147258369",
      "email": "david.abraham@education.gov.il",
      "phone": "054-1472583",
      "username": "david_abraham",
      "password": "$2b$10$3F7q/g6jxzoOebrR2XXXXX.xXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "role": "instructor",
      "status": "inactive",
      "createdDate": "2023-11-15T13:15:00Z"
    },
    {
      "id": 8,
      "firstName": "שרה",
      "lastName": "ברק",
      "idNumber": "369258147",
      "email": "sarah.barak@education.gov.il",
      "phone": "053-3692581",
      "username": "prof_barak",
      "password": "$2b$10$2E8r/h7kyapPfcsS3XXXXX.xXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "role": "senior_instructor",
      "status": "active",
      "createdDate": "2023-12-01T12:00:00Z"
    },
    {
      "id": 9,
      "firstName": "יוסי",
      "lastName": "מזרחי",
      "idNumber": "258147369",
      "email": "yossi.mizrahi@education.gov.il",
      "phone": "050-2581473",
      "username": "yossi_mizrahi",
      "password": "$2b$10$1D9s/i8lzbqQgdtT4XXXXX.xXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "role": "instructor",
      "status": "pending",
      "createdDate": "2024-03-20T07:30:00Z"
    },
    {
      "id": 10,
      "firstName": "נעמה",
      "lastName": "דוד",
      "idNumber": "741852963",
      "email": "naama.david@education.gov.il",
      "phone": "052-7418529",
      "username": "naama_david",
      "password": "$2b$10$0C0t/j9macqRhetU5XXXXX.xXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "role": "instructor",
      "status": "active",
      "createdDate": "2024-02-28T15:45:00Z"
    }
  ],
  "metadata": {
    "totalRecords": 10,
    "lastUpdated": "2024-03-21T10:00:00Z",
    "version": "1.0",
    "schema": {
      "id": "integer - מזהה ייחודי",
      "firstName": "string - שם פרטי",
      "lastName": "string - שם משפחה",
      "idNumber": "string - מספר זהות",
      "email": "string - כתובת מייל",
      "phone": "string - מספר טלפון",
      "username": "string - שם משתמש",
      "password": "string - סיסמה מוצפנת",
      "role": "enum - תפקיד (instructor/senior_instructor/admin)",
      "status": "enum - סטטוס (active/inactive/pending/suspended)",
      "createdDate": "datetime - תאריך יצירה"
    }
  }
}
